# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Claire Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  OpenAiUrl: ${{ secrets.OpenAiUrl }}
  OpenAiModel: ${{ vars.OpenAiModel }}
  OpenAiKey: ${{ secrets.OpenAiKey }}
  DeployPath: ./Claire/bin/Release/net8.0/publish
  DeployFileName: Claire.zip

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Release
      run: dotnet publish -c Release
    - name: Package
      run: zip -r ${{ env.DeployFileName }} ${{ env.DeployDir }}
    - name: Publish
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0.X-${{ github.head_ref }}
        release_name: ${{ github.event.release.name }}
        body: |
          Changes in this release:
        
        draft: true
        prerelease: false

    - name: Upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $${ env.DeployPath }}/${{ env.DeployFileName }}
        asset_name: ${{ env.DeployFileName }}
        asset_content_type: application/gzip

      
